name: Test With Pebble

on:
  workflow_call:
    inputs:
      test_command:
        type: string
        description: "The test command to run"
        required: true
        default: "deno task test:integration"

jobs:
  test-with-pebble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Run with latest stable Deno.

      - name: Start Pebble and pebble-challtestsrv
        run: deno task pebble:start --detach

      - name: Wait for Pebble to be ready
        run: |
          echo "â³ Waiting for Pebble... ðŸª¨"
          until nc -zv localhost 14000 2>/dev/null; do
            sleep 1
          done
          echo "âœ… Pebble is running!"

      - name: Wait for pebble-challtestsrv to be ready
        run: |
          echo "â³ Waiting for pebble-challtestsrv... ðŸª¨"
          until nc -zv localhost 8055 2>/dev/null; do
            sleep 1
          done
          echo "âœ… pebble-challtestsrv is running!"

      # Run the test command passed from the calling workflow
      - run: ${{ inputs.test_command }}

      - name: Stop Pebble
        run: deno task pebble:stop
